apiVersion: v1
appVersion: 0.0.78
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: croc-hunter-java
version: 0.0.78
